export const ROUTES = {
  home: "/",
  login: "/login",
  cadastro: "/cadastro",
  callback: "/callback",
  jogos: "/jogos",
  jogoDetalhe: (matchId: string) => `/jogos/${matchId}`,
  gruposFase: "/jogos/grupos",
  chaves: "/jogos/chaves",
  palpites: "/palpites",
  boloes: "/boloes",
  criarBolao: "/boloes/criar",
  entrarBolao: "/boloes/entrar",
  bolaoDetalhe: (groupId: string) => `/boloes/${groupId}`,
  bolaoChat: (groupId: string) => `/boloes/${groupId}/chat`,
  bolaoMembros: (groupId: string) => `/boloes/${groupId}/membros`,
  bolaoConfig: (groupId: string) => `/boloes/${groupId}/config`,
  disputas: "/disputas",
  novaDisputa: "/disputas/nova",
  disputaDetalhe: (disputeId: string) => `/disputas/${disputeId}`,
  ranking: "/ranking",
  palpiteCampeao: "/palpites/campeao",
  admin: "/admin",
  auditoria: "/auditoria",
  perfil: "/perfil",
  editarPerfil: "/perfil/editar",
  perfilUsuario: (userId: string) => `/perfil/${userId}`,
  notificacoes: "/notificacoes",
  convite: (code: string) => `/convite/${code}`,
} as const;

export const PUBLIC_ROUTES = [
  ROUTES.home,
  ROUTES.login,
  ROUTES.cadastro,
  ROUTES.callback,
  "/convite",
  "/api",
];
